#!/usr/bin/env python3
import pathlib
import sys


def c_ident(path: pathlib.Path) -> str:
    return ''.join(ch if ch.isalnum() else '_' for ch in path.stem) + '_capp'


def emit_array(name: str, data: bytes) -> str:
    chunks = []
    for i in range(0, len(data), 12):
        chunk = ', '.join(f'0x{b:02x}' for b in data[i:i + 12])
        chunks.append(f'    {chunk},')
    return f'static const unsigned char {name}[] = {{\n' + '\n'.join(chunks) + '\n};\n'


def main() -> int:
    if len(sys.argv) < 3:
        print('usage: embed_capps.py OUT.c INPUT.capp...', file=sys.stderr)
        return 2

    out = pathlib.Path(sys.argv[1])
    inputs = [pathlib.Path(p) for p in sys.argv[2:]]
    pieces = [
        '/* Generated by tools/embed_capps.py; edit appcompiler sources instead. */',
        '#include "kernel/apps/capp.h"',
        '',
    ]
    entries = []
    for path in inputs:
        data = path.read_bytes()
        ident = c_ident(path)
        pieces.append(emit_array(ident, data))
        entries.append((path.name, ident, len(data)))

    pieces.append('const capp_blob_t generated_capps[] = {')
    for filename, ident, size in entries:
        pieces.append(f'    {{ "{filename}", {ident}, {size}u }},')
    pieces.append('};')
    pieces.append('const u32 generated_capp_count = (u32)(sizeof(generated_capps) / sizeof(generated_capps[0]));')
    pieces.append('')

    text = '\n'.join(pieces)
    if out.exists() and out.read_text() == text:
        return 0
    out.write_text(text)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
