#!/usr/bin/env bash
# embed_capps.sh  OUT.c  INPUT.capp  [INPUT2.capp ...]
# Converts each .capp binary into a C byte-array and writes a generated_capps.c

set -e

if [ "$#" -lt 2 ]; then
    echo "usage: embed_capps.sh OUT.c INPUT.capp ..." >&2
    exit 2
fi

OUT="$1"
shift

TMP="${OUT}.tmp.$$"

{
    echo "/* Generated by tools/embed_capps.sh; edit appcompiler sources instead. */"
    echo '#include "kernel/apps/capp.h"'
    echo ""

    ENTRIES=()

    for INPUT in "$@"; do
        BASENAME=$(basename "$INPUT")
        STEM="${BASENAME%.*}"
        IDENT=$(echo "$STEM" | tr -c 'a-zA-Z0-9' '_')
        IDENT="${IDENT}_capp"
        SIZE=$(wc -c < "$INPUT")

        echo "static const unsigned char ${IDENT}[] = {"
        # xxd -i without the variable declaration — just the bytes
        od -An -tx1 -v "$INPUT" | tr ' ' '\n' | grep -v '^$' | \
        awk 'BEGIN{col=0} {printf "    0x%s,", $1; col++; if(col==12){print ""; col=0}} END{if(col>0)print ""}' 
        echo "};"
        echo ""

        ENTRIES+=("${BASENAME}|${IDENT}|${SIZE}")
    done

    echo "const capp_blob_t generated_capps[] = {"
    for ENTRY in "${ENTRIES[@]}"; do
        FILENAME="${ENTRY%%|*}"
        REST="${ENTRY#*|}"
        IDENT="${REST%%|*}"
        SZ="${REST##*|}"
        echo "    { \"${FILENAME}\", ${IDENT}, ${SZ}u },"
    done
    echo "};"
    echo "const u32 generated_capp_count = (u32)(sizeof(generated_capps) / sizeof(generated_capps[0]));"
    echo ""
} > "$TMP"

# Only overwrite if contents changed (avoids unnecessary rebuilds)
if [ -f "$OUT" ] && cmp -s "$OUT" "$TMP"; then
    rm -f "$TMP"
else
    mv "$TMP" "$OUT"
fi
